function getQuestionBankPart1_() {
  return [
  {
    "id": "Q01",
    "stage": 1,
    "topic": "3·1절",
    "dateLabel": "3월 1일",
    "stageTitle": "독립의 물결",
    "statement": "3·1운동은 1919년 3월 1일을 기점으로 일제의 식민 통치에 저항하며 전개된 독립운동이다.",
    "answer": true,
    "explanation": "3·1운동은 1919년 3월 1일을 기점으로 시작되어 전국으로 확산된 대규모 항일 독립운동입니다.",
    "sourceName": "국가기록원 · 기록으로 만나는 대한민국",
    "sourceUrl": "https://theme.archives.go.kr/next/koreaOfRecord/3_1.do"
  },
  {
    "id": "Q02",
    "stage": 1,
    "topic": "3·1절",
    "dateLabel": "3월 1일",
    "stageTitle": "독립의 물결",
    "statement": "민족대표 33인은 서울 탑골공원에서 직접 독립선언서를 발표했다.",
    "answer": false,
    "explanation": "민족대표 33인의 이름으로 된 독립선언서는 서울 인사동 태화관에서 발표되었습니다. 탑골공원에서는 학생과 시민들이 만세 시위를 전개했습니다.",
    "sourceName": "국가기록원 · 국가기록물",
    "sourceUrl": "https://theme.archives.go.kr/next/nationalArchives/subPage/nationalArchives11.do"
  },
  {
    "id": "Q03",
    "stage": 1,
    "topic": "3·1절",
    "dateLabel": "3월 1일",
    "stageTitle": "독립의 물결",
    "statement": "3·1운동은 서울에서만 일어난 지역 운동이었다.",
    "answer": false,
    "explanation": "3·1운동은 서울을 넘어 전국 각지로 퍼졌고, 국외 한인 사회의 독립운동에도 영향을 준 전 민족적 운동이었습니다.",
    "sourceName": "국사편찬위원회 · 우리역사넷",
    "sourceUrl": "https://contents.history.go.kr/mobile/kc/view.do?code=kc_age_40&levelId=kc_i400200"
  },
  {
    "id": "Q04",
    "stage": 2,
    "topic": "대한민국 임시정부 수립",
    "dateLabel": "4월 11일",
    "stageTitle": "나라의 설계도",
    "statement": "대한민국 임시정부는 1919년 중국 상하이에서 수립되었다.",
    "answer": true,
    "explanation": "3·1운동 이후 독립운동가들이 중국 상하이에 모여 대한민국 임시정부를 조직했습니다.",
    "sourceName": "국사편찬위원회 · 우리역사넷",
    "sourceUrl": "https://contents.history.go.kr/mobile/eh/view.do?code=eh_age_40&levelId=eh_r0340_0010"
  },
  {
    "id": "Q05",
    "stage": 2,
    "topic": "대한민국 임시정부 수립",
    "dateLabel": "4월 11일",
    "stageTitle": "나라의 설계도",
    "statement": "현재 대한민국 임시정부 수립 기념일은 4월 13일이다.",
    "answer": false,
    "explanation": "정부는 역사적 고증을 바탕으로 기념일을 4월 11일로 바로잡았고, 2019년 100주년 기념식부터 4월 11일에 거행하고 있습니다.",
    "sourceName": "국가보훈부 · 보도자료",
    "sourceUrl": "https://mpva.go.kr/mpva/selectBbsNttView.do?bbsNo=16&integrDeptCode=&key=77&nttNo=5299&pageIndex=189&searchCnd=all&searchCtgry=&searchKrwd="
  },
  {
    "id": "Q06",
    "stage": 2,
    "topic": "대한민국 임시정부 수립",
    "dateLabel": "4월 11일",
    "stageTitle": "나라의 설계도",
    "statement": "1919년 대한민국 임시헌장은 왕이 다스리는 군주제를 국가의 기본 형태로 삼았다.",
    "answer": false,
    "explanation": "대한민국 임시헌장은 민주공화제를 표방했습니다. 이는 국민이 주권을 가진 공화국을 지향했다는 뜻입니다.",
    "sourceName": "국사편찬위원회 · 한국사데이터베이스",
    "sourceUrl": "https://db.history.go.kr/id/ij_044_%241exp"
  },
  {
    "id": "Q07",
    "stage": 3,
    "topic": "4·19혁명",
    "dateLabel": "4월 19일",
    "stageTitle": "민주주의의 봄",
    "statement": "4·19혁명의 직접적인 도화선 가운데 하나는 1960년 3·15 부정선거였다.",
    "answer": true,
    "explanation": "자유당 정권의 3·15 부정선거에 항의하는 시위가 확산되면서 4·19혁명으로 이어졌습니다.",
    "sourceName": "국가기록원 · 기록으로 만나는 대한민국",
    "sourceUrl": "https://theme.archives.go.kr/next/koreaOfRecord/4_19.do"
  },
  {
    "id": "Q08",
    "stage": 3,
    "topic": "4·19혁명",
    "dateLabel": "4월 19일",
    "stageTitle": "민주주의의 봄",
    "statement": "4·19혁명에는 대학생만 참여했고 중·고등학생, 시민, 교수들은 참여하지 않았다.",
    "answer": false,
    "explanation": "학생들이 중심이었지만 시민과 교수 등 다양한 사람들이 참여했습니다. 4월 25일에는 교수단 시위도 있었습니다.",
    "sourceName": "국가기록원 · 4·19혁명 주요일지",
    "sourceUrl": "https://theme.archives.go.kr/next/419/info01.do?menuId=03"
  },
  {
    "id": "Q09",
    "stage": 3,
    "topic": "4·19혁명",
    "dateLabel": "4월 19일",
    "stageTitle": "민주주의의 봄",
    "statement": "4·19혁명 이후 이승만 대통령은 1960년 4월 26일 하야 성명을 발표했다.",
    "answer": true,
    "explanation": "전국으로 확산된 항의와 교수단 시위가 이어진 뒤, 이승만 대통령은 4월 26일 하야 성명을 발표했습니다.",
    "sourceName": "국가기록원 · 4·19혁명 주요일지",
    "sourceUrl": "https://theme.archives.go.kr/next/419/info01.do?menuId=03"
  },
  {
    "id": "Q10",
    "stage": 4,
    "topic": "어린이날",
    "dateLabel": "5월 5일",
    "stageTitle": "어린이의 목소리",
    "statement": "우리나라 어린이날은 처음 만들어졌을 때부터 줄곧 5월 5일이었다.",
    "answer": false,
    "explanation": "어린이날은 처음에는 5월 1일이었고 이후 5월 첫째 일요일로 바뀌었습니다. 광복 후인 1946년부터 5월 5일로 고정되었습니다.",
    "sourceName": "국가기록원 · 기록으로 만나는 대한민국",
    "sourceUrl": "https://theme.archives.go.kr/next/koreaOfRecord/childrensDay.do"
  },
  {
    "id": "Q11",
    "stage": 4,
    "topic": "어린이날",
    "dateLabel": "5월 5일",
    "stageTitle": "어린이의 목소리",
    "statement": "방정환은 우리나라 어린이날 운동과 관련이 없는 인물이다.",
    "answer": false,
    "explanation": "방정환은 어린이를 독립된 인격체로 존중해야 한다는 뜻을 널리 알리며 어린이날 운동을 이끈 핵심 인물입니다.",
    "sourceName": "국가기록원 · 뉴스레터",
    "sourceUrl": "https://theme.archives.go.kr/next/pages/new_newsletter/2015/05/sub3-2.html"
  },
  {
    "id": "Q12",
    "stage": 4,
    "topic": "어린이날",
    "dateLabel": "5월 5일",
    "stageTitle": "어린이의 목소리",
    "statement": "어린이날은 1975년부터 공휴일이 되었다.",
    "answer": true,
    "explanation": "1961년 아동복지법에 5월 5일 어린이날이 명시되었고, 1975년부터 공휴일로 지정되었습니다.",
    "sourceName": "국가기록원 · 기록으로 만나는 대한민국",
    "sourceUrl": "https://theme.archives.go.kr/next/koreaOfRecord/childrensDay.do"
  },
  {
    "id": "Q13",
    "stage": 5,
    "topic": "5·18민주화운동",
    "dateLabel": "5월 18일",
    "stageTitle": "오월의 기억",
    "statement": "5·18민주화운동은 1980년 5월 18일부터 27일까지 광주에서 전개되었다.",
    "answer": true,
    "explanation": "유네스코는 광주에서 1980년 5월 18일부터 27일까지 전개된 민주화운동 관련 기록을 설명하고 있습니다.",
    "sourceName": "유네스코 · 세계기록유산",
    "sourceUrl": "https://www.unesco.org/en/memory-world/human-rights-documentary-heritage-1980-archives-may-18th-democratic-uprising-against-military-regime"
  },
  {
    "id": "Q14",
    "stage": 5,
    "topic": "5·18민주화운동",
    "dateLabel": "5월 18일",
    "stageTitle": "오월의 기억",
    "statement": "5·18민주화운동 관련 기록물은 유네스코 세계기록유산에 등재된 적이 없다.",
    "answer": false,
    "explanation": "5·18민주화운동 관련 기록물은 2011년 유네스코 세계기록유산에 등재되었습니다.",
    "sourceName": "유네스코 · 세계기록유산",
    "sourceUrl": "https://www.unesco.org/en/memory-world/human-rights-documentary-heritage-1980-archives-may-18th-democratic-uprising-against-military-regime"
  },
  {
    "id": "Q15",
    "stage": 5,
    "topic": "5·18민주화운동",
    "dateLabel": "5월 18일",
    "stageTitle": "오월의 기억",
    "statement": "5·18민주화운동은 민주주의 요구와 무관한 지역 문화축제로 시작되었다.",
    "answer": false,
    "explanation": "5·18민주화운동은 신군부 세력을 거부하고 민주화를 요구하며 일어난 시민들의 항쟁이었습니다.",
    "sourceName": "국가보훈부 · 국립5·18민주묘지",
    "sourceUrl": "https://www.mpva.go.kr/518/contents.do?key=417"
  }
];
}
