function getQuestionBankPart2_() {
  return [
  {
    "id": "Q16",
    "stage": 6,
    "topic": "현충일",
    "dateLabel": "6월 6일",
    "stageTitle": "기억과 감사",
    "statement": "현충일은 순국선열과 전몰 호국용사의 희생을 기리기 위해 1956년에 제정되었다.",
    "answer": true,
    "explanation": "현충일은 나라를 위해 헌신하고 희생한 분들의 애국정신을 기리고 명복을 기원하기 위해 1956년에 제정되었습니다.",
    "sourceName": "국가기록원 · 기념일과 기록",
    "sourceUrl": "https://theme.archives.go.kr/next/specialDay/subInfo.do?specialDayId=00000069"
  },
  {
    "id": "Q17",
    "stage": 6,
    "topic": "현충일",
    "dateLabel": "6월 6일",
    "stageTitle": "기억과 감사",
    "statement": "현충일에는 태극기를 깃봉 끝까지 올려 경축일과 같은 방식으로 게양한다.",
    "answer": false,
    "explanation": "현충일에는 추모의 뜻을 담아 태극기를 조기로 게양합니다. 깃면의 세로 길이만큼 깃봉에서 내려 답니다.",
    "sourceName": "행정안전부 · 현충일 태극기 게양 안내",
    "sourceUrl": "https://www.mois.go.kr/html/taegeukgi/0606.html"
  },
  {
    "id": "Q18",
    "stage": 6,
    "topic": "현충일",
    "dateLabel": "6월 6일",
    "stageTitle": "기억과 감사",
    "statement": "1956년 처음 제정될 때부터 공식 명칭은 지금과 똑같이 ‘현충일’이었다.",
    "answer": false,
    "explanation": "처음 지정될 때의 명칭은 ‘현충기념일’이었고, 1975년에 ‘현충일’로 변경되었습니다.",
    "sourceName": "국가기록원 · 기념일과 기록",
    "sourceUrl": "https://theme.archives.go.kr/next/specialDay/subInfo.do?specialDayId=00000069"
  },
  {
    "id": "Q19",
    "stage": 7,
    "topic": "6·10민주항쟁",
    "dateLabel": "6월 10일",
    "stageTitle": "직선제를 향한 함성",
    "statement": "1987년 6월 10일 범국민대회를 계기로 6월민주항쟁이 본격적으로 시작되었다.",
    "answer": true,
    "explanation": "1987년 6월 10일 열린 범국민대회를 계기로 대통령 직선제와 민주화를 요구하는 시위가 전국으로 확산되었습니다.",
    "sourceName": "민주화운동기념사업회 · 오픈아카이브",
    "sourceUrl": "https://archives.kdemo.or.kr/collections/view/10000074"
  },
  {
    "id": "Q20",
    "stage": 7,
    "topic": "6·10민주항쟁",
    "dateLabel": "6월 10일",
    "stageTitle": "직선제를 향한 함성",
    "statement": "6월민주항쟁의 핵심 요구는 대통령 간선제를 그대로 유지하자는 것이었다.",
    "answer": false,
    "explanation": "6월민주항쟁의 핵심 요구 가운데 하나는 국민이 대통령을 직접 뽑는 직선제 개헌이었습니다.",
    "sourceName": "국가기록원 · 제9차 헌법개정",
    "sourceUrl": "https://theme.archives.go.kr/next/rule/sub2_10.do"
  },
  {
    "id": "Q21",
    "stage": 7,
    "topic": "6·10민주항쟁",
    "dateLabel": "6월 10일",
    "stageTitle": "직선제를 향한 함성",
    "statement": "6월민주항쟁의 결과 발표된 6·29선언에는 대통령 직선제 수용이 포함되었다.",
    "answer": true,
    "explanation": "6·29선언을 통해 대통령 직선제 개헌이 수용되었고, 이후 국민투표를 거쳐 현행 헌법의 기반이 마련되었습니다.",
    "sourceName": "국가기록원 · 헌법이야기",
    "sourceUrl": "https://theme.archives.go.kr/next/rule/sub2_10.do"
  },
  {
    "id": "Q22",
    "stage": 8,
    "topic": "제헌절",
    "dateLabel": "7월 17일",
    "stageTitle": "헌법의 나침반",
    "statement": "대한민국 제헌헌법은 1948년 7월 17일 공포되어 그날부터 효력이 발생했다.",
    "answer": true,
    "explanation": "제헌헌법은 1948년 7월 12일 국회를 통과했고, 7월 17일 서명·공포되어 그날부터 시행되었습니다.",
    "sourceName": "국가기록원 · 헌법개정사",
    "sourceUrl": "https://theme.archives.go.kr/next/rule/sub2.do"
  },
  {
    "id": "Q23",
    "stage": 8,
    "topic": "제헌절",
    "dateLabel": "7월 17일",
    "stageTitle": "헌법의 나침반",
    "statement": "제헌절은 대한민국의 국경일이 아니다.",
    "answer": false,
    "explanation": "제헌절은 3·1절, 광복절, 개천절, 한글날과 함께 대한민국의 5대 국경일 가운데 하나입니다.",
    "sourceName": "행정안전부 · 우리나라 국가상징",
    "sourceUrl": "https://www.mois.go.kr/chd/sub/a05/celebrationDay/screen.do"
  },
  {
    "id": "Q24",
    "stage": 8,
    "topic": "제헌절",
    "dateLabel": "7월 17일",
    "stageTitle": "헌법의 나침반",
    "statement": "1948년 제헌헌법은 지금까지 한 번도 개정되지 않았다.",
    "answer": false,
    "explanation": "대한민국 헌법은 여러 차례 개정되었습니다. 현행 헌법은 1987년 국민투표로 확정된 제9차 개정 헌법입니다.",
    "sourceName": "국가기록원 · 헌법이야기",
    "sourceUrl": "https://theme.archives.go.kr/next/rule/viewMain.do"
  },
  {
    "id": "Q25",
    "stage": 9,
    "topic": "광복절",
    "dateLabel": "8월 15일",
    "stageTitle": "되찾은 빛",
    "statement": "‘광복’은 빛을 되찾는다는 뜻으로, 빼앗긴 국권을 회복했다는 의미를 담고 있다.",
    "answer": true,
    "explanation": "광복은 ‘빛을 되찾다’라는 뜻이며, 일제의 식민 통치에서 벗어나 나라의 주권을 되찾았다는 의미입니다.",
    "sourceName": "국가기록원 · 오늘의 기록",
    "sourceUrl": "https://theme.archives.go.kr/next/daily/viewMain.do?selectDay=20130815"
  },
  {
    "id": "Q26",
    "stage": 9,
    "topic": "광복절",
    "dateLabel": "8월 15일",
    "stageTitle": "되찾은 빛",
    "statement": "광복절은 1945년의 해방과 1948년 대한민국 정부 수립을 함께 기념한다.",
    "answer": true,
    "explanation": "광복절은 1945년 8월 15일 국권 회복과 1948년 8월 15일 대한민국 정부 수립을 함께 경축하는 국경일입니다.",
    "sourceName": "국가기록원 · 오늘의 기록",
    "sourceUrl": "https://theme.archives.go.kr/next/daily/viewMain.do?selectDay=20130815"
  },
  {
    "id": "Q27",
    "stage": 9,
    "topic": "광복절",
    "dateLabel": "8월 15일",
    "stageTitle": "되찾은 빛",
    "statement": "현재 불리는 ‘광복절의 노래’는 1950년에 제정되었다.",
    "answer": true,
    "explanation": "국가기록원 자료에 따르면 ‘광복절의 노래’는 1950년에 제정되었습니다.",
    "sourceName": "국가기록원 · 오늘의 기록",
    "sourceUrl": "https://theme.archives.go.kr/next/daily/viewMain.do?selectDay=20130815"
  },
  {
    "id": "Q28",
    "stage": 10,
    "topic": "한글날",
    "dateLabel": "10월 9일",
    "stageTitle": "말과 글의 별빛",
    "statement": "한글날 기념식은 1945년부터 10월 9일에 열리기 시작했다.",
    "answer": true,
    "explanation": "훈민정음 해례본의 기록을 근거로 날짜를 계산해 1945년부터 10월 9일에 한글날을 기념하기 시작했습니다.",
    "sourceName": "국립국어원 · 한글날의 유래",
    "sourceUrl": "https://www.korean.go.kr/front/mcfaq/mcfaqView.do?mcfaq_seq=9028"
  },
  {
    "id": "Q29",
    "stage": 10,
    "topic": "한글날",
    "dateLabel": "10월 9일",
    "stageTitle": "말과 글의 별빛",
    "statement": "세종은 1443년에 훈민정음을 창제하고 1446년에 반포했다.",
    "answer": true,
    "explanation": "국립국어원 자료는 세종이 1443년에 훈민정음을 창제하고 1446년에 반포했다고 설명합니다.",
    "sourceName": "국립국어원 · 새국어생활",
    "sourceUrl": "https://www.korean.go.kr/nkview/nklife/2013_3/23_0302.pdf"
  },
  {
    "id": "Q30",
    "stage": 10,
    "topic": "한글날",
    "dateLabel": "10월 9일",
    "stageTitle": "말과 글의 별빛",
    "statement": "1926년 처음 열린 한글 기념식의 이름도 처음부터 ‘한글날’이었다.",
    "answer": false,
    "explanation": "1926년 첫 기념식은 ‘가갸날’이라는 이름으로 열렸습니다. 이후 ‘한글날’이라는 명칭이 자리 잡았습니다.",
    "sourceName": "국립국어원 · 한글날의 유래",
    "sourceUrl": "https://www.korean.go.kr/front/mcfaq/mcfaqView.do?mcfaq_seq=9028"
  }
];
}
